import "dotenv/config";
import { PrismaClient } from "@prisma/client";

import { loadConfig } from "../conf/config";

// tsx runs this file directly, so prisma.config.ts never loads. Resolve the
// datasource the same way the app does, before the client reads it.
const postgres = loadConfig().database.postgres;
process.env.DATABASE_URL ||= postgres.url;
process.env.DIRECT_URL ||= postgres.direct_url || postgres.url;

const prisma = new PrismaClient();

// One illustration per product, generated by scripts/generate-artwork.mts and
// served from /public. Not photographs, but each drawing is of the actual item,
// so no two listings ever share a picture.
function artFor(slug: string): string {
  return `/products/${slug}.svg`;
}

// Districts, with their Tamil spelling. The UI reads these from the row, so an
// admin adding a district gets it translated without a code change.
const regions = [
  { slug: "nilgiris", name: "Nilgiris", nameTa: "நீலகிரி" },
  { slug: "thanjavur", name: "Thanjavur", nameTa: "தஞ்சாவூர்" },
  { slug: "erode", name: "Erode", nameTa: "ஈரோடு" },
  { slug: "coorg", name: "Coorg", nameTa: "குடகு" },
  { slug: "ratnagiri", name: "Ratnagiri", nameTa: "ரத்னகிரி" },
  { slug: "himachal", name: "Himachal", nameTa: "இமாசலம்" },
];

type SeedFarmer = {
  slug: string;
  contactName: string;
  farmName: string;
  phone: string;
  email: string;
  region: string;
  about: string;
  aboutTa: string;
  status: "PENDING" | "VERIFIED" | "REJECTED" | "SUSPENDED";
  govtIdLast4?: string;
  // "Certified organic" is regulated in India. A verified farm has to carry the
  // scheme it is certified under, the certificate number and its expiry.
  certifier?: string;
  certificateNo?: string;
  certifiedUntil?: string;
  // Days before today that this farm was last checked, so the site does not show
  // the same check date on every listing.
  checkedDaysAgo?: number;
};

const farmers: SeedFarmer[] = [
  {
    slug: "sundar-organics",
    contactName: "Sundar Ramasamy",
    farmName: "Sundar Organics",
    phone: "+91 98430 11234",
    email: "sundar@sundarorganics.in",
    region: "Nilgiris",
    about:
      "Third-generation hill farm above Coonoor. Certified organic since 2016, growing leaf vegetables and tomatoes without synthetic inputs.",
    aboutTa:
      "கூனூருக்கு மேலே மூன்று தலைமுறையாக நடக்கும் மலைப் பண்ணை. 2016 முதல் இயற்கைச் சான்று உண்டு. கீரை வகைகளும் தக்காளியும் ரசாயனம் இல்லாமல் விளைகின்றன.",
    status: "VERIFIED",
    govtIdLast4: "4417",
    certifier: "NPOP / India Organic — Indocert",
    certificateNo: "IC-NPOP-2016-04417",
    certifiedUntil: "2027-03-31",
    checkedDaysAgo: 12,
  },
  {
    slug: "kaveri-farms",
    contactName: "Kaveri Devi",
    farmName: "Kaveri Delta Farms",
    phone: "+91 90031 55820",
    email: "kaveri@kaverideltafarms.in",
    region: "Thanjavur",
    about:
      "Delta paddy and pulses co-operative of eleven families. Unpolished rice milled to order, never fumigated in storage.",
    aboutTa:
      "பதினொரு குடும்பங்கள் இணைந்து நடத்தும் காவிரி டெல்டா கூட்டமைப்பு. பாலிஷ் செய்யாத அரிசியைக் கேட்கும்போது அரைத்துத் தருகிறோம். சேமிப்பில் புகையூட்டல் கிடையாது.",
    status: "VERIFIED",
    govtIdLast4: "9082",
    certifier: "PGS-India Organic — Regional Council, Thanjavur",
    certificateNo: "PGS-TN-9082-2019",
    certifiedUntil: "2026-12-31",
    checkedDaysAgo: 34,
  },
  {
    slug: "coorg-highlands",
    contactName: "Anil Bopanna",
    farmName: "Coorg Highland Estate",
    phone: "+91 97417 60455",
    email: "anil@coorghighland.in",
    region: "Coorg",
    about:
      "Shade-grown estate in Madikeri. Avocado, coffee and cold-pressed coconut oil, all wood-pressed on the estate.",
    aboutTa:
      "மடிக்கேரியில் நிழலில் வளரும் தோட்டம். வெண்ணெய்ப்பழம், காபி, தோட்டத்திலேயே மரச்செக்கில் ஆட்டிய தேங்காய் எண்ணெய்.",
    status: "VERIFIED",
    govtIdLast4: "2310",
    certifier: "NPOP / India Organic — Lacon Quality Certification",
    certificateNo: "LQC-NPOP-2310-KA",
    certifiedUntil: "2027-08-14",
    checkedDaysAgo: 6,
  },
  {
    // Listings stay hidden until an admin verifies this account.
    slug: "new-valley-produce",
    contactName: "Meera Nair",
    farmName: "New Valley Produce",
    phone: "+91 99529 74100",
    email: "meera@newvalleyproduce.in",
    region: "Erode",
    about: "Recently applied. Turmeric and banana smallholding on the Bhavani river.",
    aboutTa:
      "பவானி ஆற்றங்கரையில் மஞ்சளும் வாழையும் பயிரிடும் சிறு பண்ணை. இப்போதுதான் விண்ணப்பித்திருக்கிறார்கள்.",
    status: "PENDING",
    govtIdLast4: "7765",
  },
  {
    slug: "bhavani-riverside",
    contactName: "Selvi Murugan",
    farmName: "Bhavani Riverside Farm",
    phone: "+91 94420 33518",
    email: "selvi@bhavaniriverside.in",
    region: "Erode",
    about:
      "Twenty-two native Kangeyam cows on the Bhavani riverbank, with vegetables and citrus on the same land. Milk leaves the same morning it is drawn.",
    aboutTa:
      "பவானி ஆற்றங்கரையில் இருபத்திரண்டு காங்கேயம் நாட்டு மாடுகள். அதே நிலத்தில் காய்கறியும் எலுமிச்சை வகையும் விளைகிறது. கறந்த அன்று காலையே பால் வெளியே செல்கிறது.",
    status: "VERIFIED",
    govtIdLast4: "5194",
    certifier: "NPOP / India Organic — Indocert",
    certificateNo: "IC-NPOP-2018-05194",
    certifiedUntil: "2026-11-30",
    checkedDaysAgo: 21,
  },
  {
    slug: "konkan-alphonso",
    contactName: "Prakash Sawant",
    farmName: "Konkan Alphonso Orchard",
    phone: "+91 90280 47712",
    email: "prakash@konkanalphonso.in",
    region: "Ratnagiri",
    about:
      "Family orchard behind the Ratnagiri coast. Alphonso is picked by hand at the tree and ripened in hay, never with carbide.",
    aboutTa:
      "ரத்னகிரி கடற்கரைக்குப் பின்னால் உள்ள குடும்பத் தோட்டம். ஆல்பன்சோ மாம்பழத்தை மரத்திலேயே கையால் பறித்து, வைக்கோலில் பழுக்க வைக்கிறோம். கார்பைடு கிடையாது.",
    status: "VERIFIED",
    govtIdLast4: "6620",
    certifier: "NPOP / India Organic — SGS India",
    certificateNo: "SGS-NPOP-6620-MH",
    certifiedUntil: "2027-01-31",
    checkedDaysAgo: 48,
  },
  {
    slug: "kullu-hill-orchard",
    contactName: "Devika Thakur",
    farmName: "Kullu Hill Orchard",
    phone: "+91 98160 22904",
    email: "devika@kulluhill.in",
    region: "Himachal",
    about:
      "Cold-climate smallholding above the Kullu valley. Wild berries in season, and rock salt brought down from the old Mandi workings.",
    aboutTa:
      "குலு பள்ளத்தாக்குக்கு மேலே உள்ள குளிர்ப் பகுதிச் சிறு பண்ணை. பருவத்தில் காட்டுப் பழங்கள்; பழைய மண்டி சுரங்கத்திலிருந்து கல் உப்பு.",
    status: "VERIFIED",
    govtIdLast4: "3348",
    certifier: "PGS-India Organic — Regional Council, Kullu",
    certificateNo: "PGS-HP-3348-2021",
    certifiedUntil: "2026-09-30",
    checkedDaysAgo: 3,
  },
];

type SeedProduct = {
  name: string;
  slug: string;
  description: string;
  priceCents: number;
  unit: string;
  emoji: string;
  region: string;
  stock: number;
  isFeatured?: boolean;
  // Required: a listing without a named farm behind it is exactly what this site
  // exists to avoid.
  farmerSlug: string;
};

const catalog: Array<{
  name: string;
  slug: string;
  description: string;
  products: SeedProduct[];
}> = [
  {
    name: "Fresh Vegetables",
    slug: "fresh-vegetables",
    description: "Crisp, seasonal vegetables harvested from certified organic farms.",
    products: [
      {
        name: "Organic Baby Spinach",
        slug: "organic-baby-spinach",
        description:
          "Tender baby spinach leaves, triple-washed and ready to cook or toss into a salad.",
        priceCents: 4900,
        unit: "250 g bag",
        emoji: "\u{1F96C}",
        region: "Nilgiris",
        stock: 120,
        isFeatured: true,
        farmerSlug: "sundar-organics",
      },
      {
        name: "Heirloom Tomatoes",
        slug: "heirloom-tomatoes",
        description:
          "Vine-ripened heirloom tomatoes with a deep, sweet flavour. Grown without synthetic pesticides.",
        priceCents: 8900,
        unit: "500 g",
        emoji: "\u{1F345}",
        region: "Nilgiris",
        stock: 80,
        isFeatured: true,
        farmerSlug: "sundar-organics",
      },
      {
        name: "Rainbow Carrots",
        slug: "rainbow-carrots",
        description: "A colourful bunch of purple, yellow and orange carrots, harvested young.",
        priceCents: 7900,
        unit: "bunch",
        emoji: "\u{1F955}",
        region: "Nilgiris",
        stock: 95,
        farmerSlug: "sundar-organics",
      },
      {
        name: "Broccoli Crowns",
        slug: "broccoli-crowns",
        description: "Dense, dark-green crowns picked at peak freshness and chilled within hours.",
        priceCents: 6900,
        unit: "each",
        emoji: "\u{1F966}",
        region: "Coorg",
        stock: 60,
        farmerSlug: "coorg-highlands",
      },
      {
        name: "Snake Gourd",
        slug: "snake-gourd",
        description: "Tender pudalangai picked young, before the seeds harden. Classic poriyal material.",
        priceCents: 4400,
        unit: "500 g",
        emoji: "\u{1F952}",
        region: "Thanjavur",
        stock: 70,
        farmerSlug: "kaveri-farms",
      },
      {
        name: "Country Okra",
        slug: "country-okra",
        description: "Short, ridged native bhindi that stays firm in the pan instead of turning slimy.",
        priceCents: 5400,
        unit: "500 g",
        emoji: "\u{1FAD1}",
        region: "Thanjavur",
        stock: 88,
        farmerSlug: "kaveri-farms",
      },
      {
        name: "Curry Leaf Bunch",
        slug: "curry-leaf-bunch",
        description: "Thick, glossy karuveppilai cut the morning it ships. Never sprayed.",
        priceCents: 2500,
        unit: "100 g bunch",
        emoji: "\u{1F33F}",
        region: "Nilgiris",
        stock: 140,
        farmerSlug: "sundar-organics",
      },
      {
        name: "Purple Brinjal",
        slug: "purple-brinjal",
        description: "Small, seedy-sweet kathirikai that holds its shape through a long simmer.",
        priceCents: 4900,
        unit: "500 g",
        emoji: "\u{1F346}",
        region: "Erode",
        stock: 75,
        farmerSlug: "bhavani-riverside",
      },
    ],
  },
  {
    name: "Fresh Fruits",
    slug: "fresh-fruits",
    description: "Naturally ripened fruit with nothing sprayed on and nothing waxed over.",
    products: [
      {
        name: "Alphonso Mangoes",
        slug: "alphonso-mangoes",
        description: "Sun-ripened Alphonso mangoes, carbide-free and hand-picked at the orchard.",
        priceCents: 89900,
        unit: "box of 6",
        emoji: "\u{1F96D}",
        region: "Ratnagiri",
        stock: 40,
        isFeatured: true,
        farmerSlug: "konkan-alphonso",
      },
      {
        name: "Wild Blueberries",
        slug: "wild-blueberries",
        description: "Small, intense wild blueberries packed with antioxidants.",
        priceCents: 39900,
        unit: "150 g punnet",
        emoji: "\u{1FAD0}",
        region: "Himachal",
        stock: 55,
        farmerSlug: "kullu-hill-orchard",
      },
      {
        name: "Hass Avocados",
        slug: "hass-avocados",
        description: "Creamy Hass avocados shipped at the perfect stage of ripeness.",
        priceCents: 34900,
        unit: "pack of 3",
        emoji: "\u{1F951}",
        region: "Coorg",
        stock: 70,
        farmerSlug: "coorg-highlands",
      },
      {
        name: "Banana Robusta",
        slug: "banana-robusta",
        description: "Everyday organic bananas, ripened naturally without ethylene treatment.",
        priceCents: 5900,
        unit: "1 kg",
        emoji: "\u{1F34C}",
        region: "Thanjavur",
        stock: 150,
        farmerSlug: "kaveri-farms",
      },
      {
        name: "Nendran Banana",
        slug: "nendran-banana",
        description: "Firm Kerala nendran, the right variety for chips or a steamed breakfast.",
        priceCents: 8900,
        unit: "1 kg",
        emoji: "\u{1F34C}",
        region: "Erode",
        stock: 60,
        farmerSlug: "new-valley-produce",
      },
      {
        name: "Panneer Grapes",
        slug: "panneer-grapes",
        description: "Seeded Cumbum valley grapes with a musky finish. Sold loose, never waxed.",
        priceCents: 14900,
        unit: "500 g",
        emoji: "\u{1F347}",
        region: "Nilgiris",
        stock: 52,
        farmerSlug: "sundar-organics",
      },
      {
        name: "Sweet Lime",
        slug: "sweet-lime",
        description: "Thin-skinned mosambi that juices cleanly without turning bitter.",
        priceCents: 9900,
        unit: "1 kg",
        emoji: "\u{1F34A}",
        region: "Erode",
        stock: 96,
        farmerSlug: "bhavani-riverside",
      },
      {
        name: "Guava, Allahabad Safeda",
        slug: "guava-allahabad-safeda",
        description: "Crisp white-fleshed guava picked at the snap stage, not the soft stage.",
        priceCents: 7900,
        unit: "1 kg",
        emoji: "\u{1F7E2}",
        region: "Coorg",
        stock: 64,
        farmerSlug: "coorg-highlands",
      },
    ],
  },
  {
    name: "Dairy & Eggs",
    slug: "dairy-and-eggs",
    description: "From pasture-raised herds and free-roaming flocks.",
    products: [
      {
        name: "A2 Whole Milk",
        slug: "a2-whole-milk",
        description: "Single-origin A2 milk from grass-fed cows, gently pasteurised.",
        priceCents: 9900,
        unit: "1 L",
        emoji: "\u{1F95B}",
        region: "Erode",
        stock: 100,
        isFeatured: true,
        farmerSlug: "bhavani-riverside",
      },
      {
        name: "Free-Range Eggs",
        slug: "free-range-eggs",
        description: "Rich orange yolks from hens raised outdoors on an organic feed.",
        priceCents: 12900,
        unit: "dozen",
        emoji: "\u{1F95A}",
        region: "Erode",
        stock: 85,
        farmerSlug: "bhavani-riverside",
      },
      {
        name: "Cultured Farm Butter",
        slug: "cultured-farm-butter",
        description: "Slow-cultured butter churned in small batches with just cream and salt.",
        priceCents: 27900,
        unit: "200 g",
        emoji: "\u{1F9C8}",
        region: "Erode",
        stock: 45,
        farmerSlug: "bhavani-riverside",
      },
      {
        name: "Set Curd",
        slug: "set-curd",
        description: "Thick pot-set curd from the same A2 herd, cultured overnight and never stirred.",
        priceCents: 6900,
        unit: "400 g pot",
        emoji: "\u{1F368}",
        region: "Erode",
        stock: 70,
        farmerSlug: "bhavani-riverside",
      },
      {
        name: "Bilona Cow Ghee",
        slug: "bilona-cow-ghee",
        description: "Hand-churned from cultured curd, not cream. Grainy, deep yellow, strongly aromatic.",
        priceCents: 89900,
        unit: "500 ml",
        emoji: "\u{1F36F}",
        region: "Erode",
        stock: 30,
        isFeatured: true,
        farmerSlug: "bhavani-riverside",
      },
    ],
  },
  {
    name: "Grains & Pulses",
    slug: "grains-and-pulses",
    description: "Stone-milled grains and single-origin pulses, stored without fumigation.",
    products: [
      {
        name: "Sonamasuri Brown Rice",
        slug: "sonamasuri-brown-rice",
        description: "Unpolished Sonamasuri rice with a soft bite and a low glycaemic index.",
        priceCents: 54900,
        unit: "5 kg",
        emoji: "\u{1F35A}",
        region: "Thanjavur",
        stock: 35,
        isFeatured: true,
        farmerSlug: "kaveri-farms",
      },
      {
        name: "Whole Red Lentils",
        slug: "whole-red-lentils",
        description: "Chemical-free red lentils that cook down fast into a silky dal.",
        priceCents: 17900,
        unit: "1 kg",
        emoji: "\u{1FAD8}",
        region: "Thanjavur",
        stock: 65,
        farmerSlug: "kaveri-farms",
      },
      {
        name: "Stone-Milled Wheat Flour",
        slug: "stone-milled-wheat-flour",
        description: "Chakki-milled whole wheat flour with the bran and germ left intact.",
        priceCents: 31900,
        unit: "5 kg",
        emoji: "\u{1F33E}",
        region: "Thanjavur",
        stock: 50,
        farmerSlug: "kaveri-farms",
      },
      {
        name: "Little Millet",
        slug: "little-millet",
        description: "Samai from a rainfed plot, hulled but unpolished. Cooks like a short-grain rice.",
        priceCents: 21900,
        unit: "2 kg",
        emoji: "\u{1F33E}",
        region: "Thanjavur",
        stock: 44,
        farmerSlug: "kaveri-farms",
      },
      {
        name: "Black Urad Whole",
        slug: "black-urad-whole",
        description: "Skin-on urad for a properly dark, tempered dal. Sorted by hand, never polished.",
        priceCents: 19900,
        unit: "1 kg",
        emoji: "\u{1FAD8}",
        region: "Thanjavur",
        stock: 58,
        farmerSlug: "kaveri-farms",
      },
    ],
  },
  {
    name: "Pantry Staples",
    slug: "pantry-staples",
    description: "Cold-pressed oils, raw honey and everyday essentials without additives.",
    products: [
      {
        name: "Cold-Pressed Coconut Oil",
        slug: "cold-pressed-coconut-oil",
        description: "Wood-pressed virgin coconut oil with its natural aroma preserved.",
        priceCents: 39900,
        unit: "500 ml",
        emoji: "\u{1F965}",
        region: "Coorg",
        stock: 48,
        farmerSlug: "coorg-highlands",
      },
      {
        name: "Raw Forest Honey",
        slug: "raw-forest-honey",
        description: "Unheated, unfiltered multi-floral honey collected from forest hives.",
        priceCents: 54900,
        unit: "500 g",
        emoji: "\u{1F36F}",
        region: "Nilgiris",
        stock: 42,
        isFeatured: true,
        farmerSlug: "sundar-organics",
      },
      {
        name: "Himalayan Rock Salt",
        slug: "himalayan-rock-salt",
        description: "Hand-mined pink rock salt, unrefined and free of anti-caking agents.",
        priceCents: 8900,
        unit: "1 kg",
        emoji: "\u{1F9C2}",
        region: "Himachal",
        stock: 90,
        farmerSlug: "kullu-hill-orchard",
      },
      {
        name: "Wood-Pressed Groundnut Oil",
        slug: "wood-pressed-groundnut-oil",
        description: "Chekku oil pressed slowly so it keeps its colour and its smell. Unrefined.",
        priceCents: 44900,
        unit: "1 L",
        emoji: "\u{1F95C}",
        region: "Coorg",
        stock: 40,
        farmerSlug: "coorg-highlands",
      },
      {
        name: "Palm Jaggery Blocks",
        slug: "palm-jaggery-blocks",
        description: "Karupatti tapped from palmyra, boiled down with nothing added. Smoky and dark.",
        priceCents: 24900,
        unit: "500 g",
        emoji: "\u{1F36B}",
        region: "Thanjavur",
        stock: 62,
        farmerSlug: "kaveri-farms",
      },
      {
        name: "Single-Origin Filter Coffee",
        slug: "single-origin-filter-coffee",
        description: "Shade-grown arabica with 20% chicory, roasted dark and ground for a steel filter.",
        priceCents: 39900,
        unit: "500 g",
        emoji: "\u{2615}",
        region: "Coorg",
        stock: 55,
        isFeatured: true,
        farmerSlug: "coorg-highlands",
      },
      {
        name: "Raw Turmeric Fingers",
        slug: "raw-turmeric-fingers",
        description: "High-curcumin Erode turmeric, sun-dried whole so you can grind it yourself.",
        priceCents: 17900,
        unit: "500 g",
        emoji: "\u{1F7E1}",
        region: "Erode",
        stock: 48,
        farmerSlug: "new-valley-produce",
      },
    ],
  },
];

// Tamil catalogue copy, keyed by slug. Written to the *Ta columns; anything not
// listed here falls back to the English column at read time.
const categoryTa: Record<string, { name: string; description: string }> = {
  "fresh-vegetables": {
    name: "காய்கறிகள்",
    description: "இயற்கைப் பண்ணைகளில் பறித்த பருவகால காய்கறிகள்.",
  },
  "fresh-fruits": {
    name: "பழங்கள்",
    description: "மரத்திலேயே பழுத்த பழங்கள். மெழுகும் இல்லை, மருந்தும் இல்லை.",
  },
  "dairy-and-eggs": {
    name: "பால், முட்டை",
    description: "மேய்ச்சலில் வளரும் மாடுகள், திறந்தவெளியில் சுற்றும் கோழிகள்.",
  },
  "grains-and-pulses": {
    name: "தானியம், பருப்பு",
    description: "கல்லில் அரைத்த தானியங்கள், ஒரே பண்ணைப் பருப்பு. புகையூட்டாமல் சேமிப்பு.",
  },
  "pantry-staples": {
    name: "சமையலறைப் பொருட்கள்",
    description: "மரச்செக்கு எண்ணெய், சுத்தமான தேன், தினசரித் தேவைகள். சேர்க்கைகள் இல்லை.",
  },
};

const productTa: Record<string, { name: string; description: string }> = {
  "organic-baby-spinach": {
    name: "இளம் பசலைக் கீரை",
    description: "மென்மையான இளம் பசலை இலைகள். மூன்று முறை கழுவி அனுப்புகிறோம்.",
  },
  "heirloom-tomatoes": {
    name: "நாட்டுத் தக்காளி",
    description: "கொடியிலேயே பழுத்த நாட்டுத் தக்காளி. ஆழமான இனிப்புச் சுவை, ரசாயனம் இல்லை.",
  },
  "rainbow-carrots": {
    name: "வண்ணக் கேரட்",
    description: "ஊதா, மஞ்சள், ஆரஞ்சு கேரட் ஒன்றாக ஒரு கட்டு. இளசாகப் பறித்தது.",
  },
  "broccoli-crowns": {
    name: "ப்ரோக்கோலி",
    description: "அடர் பச்சை ப்ரோக்கோலி. பறித்த சில மணி நேரத்திலேயே குளிர்வைக்கிறோம்.",
  },
  "snake-gourd": {
    name: "புடலங்காய்",
    description: "விதை இறுகும் முன் பறித்த இளம் புடலை. பொரியலுக்கு ஏற்றது.",
  },
  "little-millet": {
    name: "சாமை",
    description: "மானாவாரி நிலத்துச் சாமை. உமி நீக்கியது, பாலிஷ் இல்லை.",
  },
  "black-urad-whole": {
    name: "முழு கருப்பு உளுந்து",
    description: "தோல் நீக்காத உளுந்து. கையால் பிரித்தது, பாலிஷ் செய்யவில்லை.",
  },
  "country-okra": {
    name: "நாட்டு வெண்டைக்காய்",
    description: "குட்டையான நாட்டு வெண்டை. வதக்கும்போது வழுவழுப்பாகாமல் இறுகி இருக்கும்.",
  },
  "curry-leaf-bunch": {
    name: "கருவேப்பிலைக் கட்டு",
    description: "அனுப்பும் அன்று காலை வெட்டிய தடித்த கருவேப்பிலை. மருந்து அடிப்பதில்லை.",
  },
  "purple-brinjal": {
    name: "ஊதா கத்திரிக்காய்",
    description: "சிறிய இனிப்புச் சுவைக் கத்திரி. நீண்ட நேரம் கொதித்தாலும் உருவம் கெடாது.",
  },
  "alphonso-mangoes": {
    name: "ஆல்பன்சோ மாம்பழம்",
    description: "வெயிலில் பழுத்த ஆல்பன்சோ. தோட்டத்திலேயே கையால் பறித்தது, கார்பைடு இல்லை.",
  },
  "wild-blueberries": {
    name: "காட்டு புளூபெர்ரி",
    description: "சிறிய, சுவை அடர்ந்த காட்டு புளூபெர்ரி.",
  },
  "hass-avocados": {
    name: "ஹாஸ் வெண்ணெய்ப்பழம்",
    description: "கிரீம் போன்ற ஹாஸ் வெண்ணெய்ப்பழம். சரியான பக்குவத்தில் அனுப்புகிறோம்.",
  },
  "banana-robusta": {
    name: "ரோபஸ்டா வாழைப்பழம்",
    description: "தினசரி இயற்கை வாழைப்பழம். மருந்து இல்லாமல் தானாகப் பழுத்தது.",
  },
  "nendran-banana": {
    name: "நேந்திரம் பழம்",
    description: "இறுக்கமான கேரள நேந்திரம். சிப்ஸுக்கும் ஆவியில் வேகவைக்கவும் ஏற்றது.",
  },
  "panneer-grapes": {
    name: "பன்னீர் திராட்சை",
    description: "கம்பம் பள்ளத்தாக்கு விதைத் திராட்சை. தளர்வாக விற்கிறோம், மெழுகு இல்லை.",
  },
  "sweet-lime": {
    name: "சாத்துக்குடி",
    description: "மெல்லிய தோல் கொண்ட சாத்துக்குடி. கசக்காமல் நன்றாகச் சாறு பிழியும்.",
  },
  "guava-allahabad-safeda": {
    name: "கொய்யா, அலகாபாத் சபேதா",
    description: "வெள்ளைச் சதை கொண்ட மொறுமொறுப்பான கொய்யா. மென்மையாகும் முன் பறித்தது.",
  },
  "a2-whole-milk": {
    name: "A2 முழு பால்",
    description: "புல் மேய்ந்த மாடுகளின் A2 பால், மிதமாகக் காய்ச்சியது.",
  },
  "free-range-eggs": {
    name: "நாட்டுக் கோழி முட்டை",
    description: "வெளியே சுற்றி மேயும் கோழிகளின் முட்டை. அடர் ஆரஞ்சு நிற மஞ்சள் கரு.",
  },
  "cultured-farm-butter": {
    name: "பண்ணை வெண்ணெய்",
    description: "சிறு தொகுதிகளாகக் கடைந்த வெண்ணெய். கிரீமும் உப்பும் மட்டுமே.",
  },
  "set-curd": {
    name: "கட்டித் தயிர்",
    description: "அதே A2 பாலில் இரவு முழுக்க உறைந்த கெட்டித் தயிர். கலக்கவில்லை.",
  },
  "bilona-cow-ghee": {
    name: "பிலோனா பசு நெய்",
    description: "கிரீமில் அல்ல, தயிரில் இருந்து கையால் கடைந்த நெய். அடர் மஞ்சள், நல்ல வாசனை.",
  },
  "sonamasuri-brown-rice": {
    name: "சோனாமசூரி கைக்குத்தல் அரிசி",
    description: "பாலிஷ் செய்யாத சோனாமசூரி. மென்மையான பதம், குறைந்த கிளைசெமிக் அளவு.",
  },
  "whole-red-lentils": {
    name: "முழு மசூர் பருப்பு",
    description: "ரசாயனம் இல்லாத மசூர் பருப்பு. விரைவில் வெந்து மென்மையான பருப்பாகும்.",
  },
  "stone-milled-wheat-flour": {
    name: "கல் மில் கோதுமை மாவு",
    description: "சக்கி மில்லில் அரைத்த முழு கோதுமை மாவு. தவிடும் முளையும் அப்படியே.",
  },
  "cold-pressed-coconut-oil": {
    name: "மரச்செக்கு தேங்காய் எண்ணெய்",
    description: "மரச்செக்கில் ஆட்டிய கன்னி தேங்காய் எண்ணெய். இயற்கை வாசனை அப்படியே.",
  },
  "raw-forest-honey": {
    name: "காட்டுத் தேன்",
    description: "காய்ச்சாத, வடிகட்டாத பல்பூத் தேன். காட்டுக் கூடுகளிலிருந்து சேகரித்தது.",
  },
  "himalayan-rock-salt": {
    name: "இமய கல் உப்பு",
    description: "கையால் எடுத்த இளஞ்சிவப்புக் கல் உப்பு. சுத்திகரிக்காதது, சேர்க்கைகள் இல்லை.",
  },
  "wood-pressed-groundnut-oil": {
    name: "மரச்செக்கு கடலை எண்ணெய்",
    description: "மெதுவாக ஆட்டிய செக்கு எண்ணெய். நிறமும் வாசனையும் அப்படியே.",
  },
  "palm-jaggery-blocks": {
    name: "கருப்பட்டி",
    description: "பனையிலிருந்து இறக்கிய பதநீரைக் காய்ச்சியது. எதுவும் சேர்க்கவில்லை.",
  },
  "single-origin-filter-coffee": {
    name: "பில்டர் காபிப் பொடி",
    description: "நிழலில் வளர்ந்த அரேபிக்கா, 20% சிக்கரியுடன். டிகாக்ஷனுக்கு ஏற்ற அரவை.",
  },
  "raw-turmeric-fingers": {
    name: "பச்சை மஞ்சள் கிழங்கு",
    description: "குர்குமின் அதிகமுள்ள ஈரோட்டு மஞ்சள். வெயிலில் முழுசாக உலர்த்தியது.",
  },
};

async function main() {
  const farmerIdBySlug = new Map<string, string>();

  // Districts are their own table, so the Tamil spelling lives with the data
  // rather than in a hard-coded map in the UI layer.
  const regionIdByName = new Map<string, string>();
  for (const region of regions) {
    const saved = await prisma.region.upsert({
      where: { slug: region.slug },
      update: { name: region.name, nameTa: region.nameTa },
      create: region,
      select: { id: true, name: true },
    });
    regionIdByName.set(saved.name, saved.id);
  }

  for (const farmer of farmers) {
    const { status, certifiedUntil, checkedDaysAgo, region, ...rest } = farmer;
    const regionId = regionIdByName.get(region);
    if (!regionId) throw new Error(`Unknown region "${region}" on ${farmer.slug}`);

    const data = {
      ...rest,
      regionId,
      status,
      photoUrl: `/farms/${farmer.slug}.svg`,
      certifiedUntil: certifiedUntil ? new Date(certifiedUntil) : null,
      verifiedAt:
        status === "VERIFIED"
          ? new Date(Date.now() - (checkedDaysAgo ?? 0) * 86_400_000)
          : null,
    };
    const saved = await prisma.farmer.upsert({
      where: { slug: farmer.slug },
      update: data,
      create: data,
    });
    farmerIdBySlug.set(farmer.slug, saved.id);
  }

  for (const category of catalog) {
    const { products, ...categoryData } = category;
    const ta = categoryTa[categoryData.slug];
    const data = {
      ...categoryData,
      nameTa: ta?.name ?? null,
      descriptionTa: ta?.description ?? null,
    };

    const savedCategory = await prisma.category.upsert({
      where: { slug: categoryData.slug },
      update: data,
      create: data,
    });

    for (const product of products) {
      const { farmerSlug, ...productData } = product;
      const farmerId = farmerIdBySlug.get(farmerSlug);
      if (!farmerId) throw new Error(`Unknown farmerSlug "${farmerSlug}" on ${product.slug}`);

      const art = artFor(product.slug);
      const productTamil = productTa[product.slug];
      const { region: productRegion, ...restProduct } = productData;
      const data = {
        ...restProduct,
        // The listing's district is the farm's district; storing a second copy
        // is how they drifted apart before.
        regionId: productRegion ? (regionIdByName.get(productRegion) ?? null) : null,
        nameTa: productTamil?.name ?? null,
        descriptionTa: productTamil?.description ?? null,
        imageUrl: art,
        categoryId: savedCategory.id,
        farmerId,
      };
      const saved = await prisma.product.upsert({
        where: { slug: product.slug },
        update: data,
        create: data,
      });

      // One image per product. The old seed fabricated three "views" out of
      // unrelated clipart, which the gallery then presented as camera angles.
      await prisma.productImage.deleteMany({ where: { productId: saved.id } });
      await prisma.productImage.create({
        data: { productId: saved.id, url: art, position: 0, alt: null },
      });
    }
  }

  const [categories, products, farmerCount, verified, images] = await Promise.all([
    prisma.category.count(),
    prisma.product.count(),
    prisma.farmer.count(),
    prisma.farmer.count({ where: { status: "VERIFIED" } }),
    prisma.productImage.count(),
  ]);

  console.log(
    `Seed complete: ${categories} categories, ${products} products, ${images} images, ` +
      `${farmerCount} farmers (${verified} verified).`,
  );
}

main()
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
